default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  host: localhost
  port: 5432
  pool: 5

development:
  <<: *default
  database: phschool_development
  password: postgres

test:
  <<: *default
  database: phschool_test
  password: postgres

production:
  <<: *default
  database: phschool_production
  password: postgres
